// build-models.js
import fs   from 'fs';
import path from 'path';
import puppeteer from 'puppeteer';

const ASSETS = path.resolve(process.cwd(), 'public/assets');
const OUT_SRC = path.resolve(process.cwd(), 'src', 'glb_data.js');

const delay = ms => new Promise(resolve => setTimeout(resolve, ms));

const mvUmd = fs.readFileSync(
  path.join(process.cwd(),
            'node_modules/@google/model-viewer/dist/model-viewer.min.js'),
  'utf8'
);

async function generateThumbnail(glbFile, posterFile) {
  console.log(`\n[thumb] Generating ${posterFile} from ${glbFile}`);

  console.log(`[thumb] Embedding ${glbFile} as data URI…`);
  const glb = fs.readFileSync(glbFile);
  const base64 = glb.toString('base64');
  const dataUri = `data:model/gltf-binary;base64,${base64}`;

  // 1) launch browser
  console.log('[thumb] → launching browser…');
  const browser = await puppeteer.launch({
    headless: true,
    executablePath: process.env.CHROME_PATH || '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
    args: ['--no-sandbox', '--disable-setuid-sandbox']
  });
  console.log('[thumb] ✓ browser launched');

  const page = await browser.newPage();

  // 2) pipe page console into our logs
  page.on('console', msg => console.log(`[PAGE] ${msg.text()}`));
  page.on('pageerror', err => console.error('[PAGE ERROR]', err));
  page.on('requestfailed', req =>
    console.warn(`[PAGE REQUEST FAILED] ${req.url()} – ${req.failure()?.errorText}`)
  );

  // 3) set content & wait for the <model-viewer> tag to exist
  console.log('[thumb] → setting HTML content…');
  const html = `
    <html><body style="margin:0">
      <script type="module">
      ${mvUmd}
    </script>
      <model-viewer
        style="display:block; width:512px; height:512px"
        src="${dataUri}"
        auto-rotate
        camera-controls
      ></model-viewer>
    </body></html>
  `;

  await page.setContent(html, { waitUntil: 'networkidle2' });
  await page.waitForSelector('model-viewer', { timeout: 60000 });

  console.log('[thumb] → waiting for modelComplete…');
  try {
    await page.waitForFunction(
      'document.querySelector("model-viewer").modelComplete === true',
      { timeout: 10000 }
    );
  } catch {
    console.warn('[thumb] ⚠ modelComplete timed out; waiting 5s fallback');
    await delay(5000);
  }

  console.log('[thumb] → screenshot…');
  const mvHandle = await page.$('model-viewer');
  try {
    await mvHandle.screenshot({ path: posterFile, omitBackground: true });
  } catch (err) {
    console.warn(`[thumb] element screenshot failed (${err.message}); using viewport`);
    await page.screenshot({
      path: posterFile,
      clip: { x: 0, y: 0, width: 512, height: 512 },
      omitBackground: true,
    });
  }
  console.log(`[thumb] ✓ saved poster: ${posterFile}`);

  await browser.close();
  console.log('[thumb] browser closed\n');
}

async function main() {
  const all = fs.readdirSync(ASSETS).filter(f => f.endsWith('.glb'));
  const models = [];

  for (const name of all) {
    const id = path.basename(name, '.glb');
    const src    = `assets/${name}`;
    const poster = `assets/poster_${id}.png`;
    const posterPath = path.join(ASSETS, `poster_${id}.png`);

    models.push({
      id,
      source: src,
      poster,
      title: id.replace(/[_-]/g, ' '),
      description: '',
      preview: true,
      // you can fill in defaults for usdz, author, etc.
    });

    if (!fs.existsSync(posterPath)) {
      console.log(`  ↳ generating thumbnail for ${name}`);
      await generateThumbnail(
        path.join(ASSETS, name),
        posterPath
      );
    }
  }

  // write out a single JS module
  const content = `// this file is auto-generated by build-models.js
export const modelData = ${JSON.stringify(models, null, 2)};\n`;
  fs.writeFileSync(OUT_SRC, content);
}

main().catch(err => {
  console.error(err);
  process.exit(1);
});
