// build-models.js
import fs from 'fs';
import path from 'path';
import puppeteer from 'puppeteer';

// Directories
const MODELS_DIR   = path.resolve(process.cwd(), 'public/assets/models');
const POSTERS_DIR  = path.resolve(process.cwd(), 'public/assets/posters');
const METADATA_DIR = path.resolve(process.cwd(), 'public/assets/metadata');
const OUT_SRC      = path.resolve(process.cwd(), 'src', 'glb_data.js');

// Simple sleep helper
const delay = ms => new Promise(res => setTimeout(res, ms));

// Read the ES module build of model-viewer
const mvESM = fs.readFileSync(
  path.join(
    process.cwd(),
    'node_modules/@google/model-viewer/dist/model-viewer.min.js'
  ),
  'utf8'
);

// Ensure asset dirs exist
[MODELS_DIR, POSTERS_DIR, METADATA_DIR].forEach(dir => {
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
});

async function generateThumbnail(glbFile, posterFile) {
  console.log(`\n[thumb] Generating ${posterFile} from ${glbFile}`);

  console.log(`[thumb] Embedding ${glbFile} as data URI…`);
  const glb = fs.readFileSync(glbFile);
  const base64 = glb.toString('base64');
  const dataUri = `data:model/gltf-binary;base64,${base64}`;

  console.log('[thumb] → launching browser…');
  const browser = await puppeteer.launch({
    headless: true,
    executablePath:
      process.env.CHROME_PATH ||
      '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
    args: ['--no-sandbox', '--disable-setuid-sandbox'],
  });
  console.log('[thumb] ✓ browser launched');

  const page = await browser.newPage();
  page.on('console', msg => console.log(`[PAGE] ${msg.text()}`));
  page.on('pageerror', err => console.error('[PAGE ERROR]', err));
  page.on('requestfailed', req =>
    console.warn(`[PAGE REQUEST FAILED] ${req.url()} – ${req.failure()?.errorText}`)
  );

  console.log('[thumb] → setting HTML content…');
  const html = `
<html>
  <body style="margin:0">
    <script type="module">
${mvESM}
    </script>
    <model-viewer
      style="display:block; width:512px; height:512px"
      src="${dataUri}"
      auto-rotate
      camera-controls
    ></model-viewer>
  </body>
</html>
`;

  await page.setContent(html, { waitUntil: 'networkidle2' });
  await page.waitForSelector('model-viewer', { timeout: 60000 });

  console.log('[thumb] → waiting for modelComplete…');
  try {
    await page.waitForFunction(
      'document.querySelector("model-viewer").modelComplete === true',
      { timeout: 10000 }
    );
    console.log('[thumb] ✓ modelComplete!');
  } catch {
    console.warn('[thumb] ⚠ modelComplete timed out; waiting 5s fallback');
    await delay(5000);
  }

  console.log('[thumb] → screenshot…');
  const mvHandle = await page.$('model-viewer');
  try {
    await mvHandle.screenshot({ path: posterFile, omitBackground: true });
  } catch (err) {
    console.warn(`[thumb] element screenshot failed (${err.message}); fallback to viewport`);
    await page.screenshot({
      path: posterFile,
      clip: { x: 0, y: 0, width: 512, height: 512 },
      omitBackground: true,
    });
  }

  console.log(`[thumb] ✓ saved poster: ${posterFile}`);
  await browser.close();
  console.log('[thumb] browser closed');
}

async function main() {
  const files = fs.readdirSync(MODELS_DIR).filter(f => f.endsWith('.glb'));
  const models = [];

  for (const name of files) {
    const id = path.basename(name, '.glb');
    const src = `assets/models/${name}`;
    const posterRel = `assets/posters/poster_${id}.png`;
    const posterPath = path.join(POSTERS_DIR, `poster_${id}.png`);

    // Load or create metadata
    const metaFile = path.join(METADATA_DIR, `${id}.json`);
    if (!fs.existsSync(metaFile)) {
      const def = {
        id,
        title: id.replace(/[_-]/g, ' '),
        description: '',
        preview: true,
        author: '',
        usdz: '',
      };
      fs.writeFileSync(metaFile, JSON.stringify(def, null, 2));
      console.log(`Created metadata: ${metaFile}`);
    }
    const meta = JSON.parse(fs.readFileSync(metaFile, 'utf8'));

    // Override source & poster
    meta.source = src;
    meta.poster = posterRel;
    models.push(meta);

    if (!fs.existsSync(posterPath)) {
      await generateThumbnail(
        path.join(MODELS_DIR, name),
        posterPath
      );
    }
  }

  const content = `// Auto-generated by build-models.js
export const modelData = ${JSON.stringify(models, null, 2)};\n`;
  fs.writeFileSync(OUT_SRC, content);
}

main().catch(err => {
  console.error(err);
  process.exit(1);
});
