// Auto-generated by build-models.js
export const modelData = [
  {
    "id": "archway_FILE250630-092430F",
    "title": "Archway",
    "description": "",
    "preview": true,
    "author": "Jay",
    "usdz": "",
    "source": "assets/models/archway_FILE250630-092430F.glb",
    "poster": "assets/posters/poster_archway_FILE250630-092430F.png"
  },
  {
    "id": "baby_coral",
    "title": "Baby Coral",
    "description": "",
    "preview": true,
    "author": "",
    "usdz": "",
    "source": "assets/models/baby_coral.glb",
    "poster": "assets/posters/poster_baby_coral.png"
  },
  {
    "id": "beautiful",
    "title": "Beautiful",
    "description": "",
    "preview": true,
    "author": "",
    "usdz": "",
    "source": "assets/models/beautiful.glb",
    "poster": "assets/posters/poster_beautiful.png"
  },
  {
    "id": "bell",
    "title": "Bell",
    "description": "",
    "preview": true,
    "author": "",
    "usdz": "",
    "source": "assets/models/bell.glb",
    "poster": "assets/posters/poster_bell.png"
  },
  {
    "id": "big-brain_P6300418",
    "title": "Big Brain",
    "description": "",
    "preview": true,
    "author": "Paula",
    "usdz": "",
    "source": "assets/models/big-brain_P6300418.glb",
    "poster": "assets/posters/poster_big-brain_P6300418.png"
  },
  {
    "id": "big_gulp_coral",
    "title": "Big Gulp Coral",
    "description": "",
    "preview": true,
    "author": "",
    "usdz": "",
    "source": "assets/models/big_gulp_coral.glb",
    "poster": "assets/posters/poster_big_gulp_coral.png"
  },
  {
    "id": "big_gulp_nearby_rocks",
    "title": "Big Gulp Nearby Rocks",
    "description": "",
    "preview": true,
    "author": "",
    "usdz": "",
    "source": "assets/models/big_gulp_nearby_rocks.glb",
    "poster": "assets/posters/poster_big_gulp_nearby_rocks.png"
  },
  {
    "id": "block-arch_P6300303",
    "title": "Block Arch",
    "description": "",
    "preview": true,
    "author": "",
    "usdz": "",
    "source": "assets/models/block-arch_P6300303.glb",
    "poster": "assets/posters/poster_block-arch_P6300303.png"
  },
  {
    "id": "boule",
    "title": "Boule",
    "description": "",
    "preview": true,
    "author": "",
    "usdz": "",
    "source": "assets/models/boule.glb",
    "poster": "assets/posters/poster_boule.png"
  },
  {
    "id": "brain-n-rocks_FILE250630-094721F",
    "title": "Brain 'n' Rocks",
    "description": "",
    "preview": true,
    "author": "Jay",
    "usdz": "",
    "source": "assets/models/brain-n-rocks_FILE250630-094721F.glb",
    "poster": "assets/posters/poster_brain-n-rocks_FILE250630-094721F.png"
  },
  {
    "id": "bumps",
    "title": "Bumps",
    "description": "",
    "preview": true,
    "author": "",
    "usdz": "",
    "source": "assets/models/bumps.glb",
    "poster": "assets/posters/poster_bumps.png"
  },
  {
    "id": "columnar-coral_FILE250704-094129F",
    "title": "Columnar Coral",
    "description": "",
    "preview": true,
    "author": "Jay",
    "usdz": "",
    "source": "assets/models/columnar-coral_FILE250704-094129F.glb",
    "poster": "assets/posters/poster_columnar-coral_FILE250704-094129F.png"
  },
  {
    "id": "coral-variety-2_P6300279",
    "title": "Coral Variety 2",
    "description": "",
    "preview": true,
    "author": "Paula",
    "usdz": "",
    "source": "assets/models/coral-variety-2_P6300279.glb",
    "poster": "assets/posters/poster_coral-variety-2_P6300279.png"
  },
  {
    "id": "coral-variety_GH010101",
    "title": "Coral Variety",
    "description": "",
    "preview": true,
    "author": "Grace",
    "usdz": "",
    "source": "assets/models/coral-variety_GH010101.glb",
    "poster": "assets/posters/poster_coral-variety_GH010101.png"
  },
  {
    "id": "coral_cliff",
    "title": "Coral Cliff",
    "description": "",
    "preview": true,
    "author": "",
    "usdz": "",
    "source": "assets/models/coral_cliff.glb",
    "poster": "assets/posters/poster_coral_cliff.png"
  },
  {
    "id": "cucumber-mound_FILE250630-094443F",
    "title": "Cucumber Mound",
    "description": "",
    "preview": true,
    "author": "Jay",
    "usdz": "",
    "source": "assets/models/cucumber-mound_FILE250630-094443F.glb",
    "poster": "assets/posters/poster_cucumber-mound_FILE250630-094443F.png"
  },
  {
    "id": "fish-house",
    "title": "Fish House",
    "description": "",
    "preview": true,
    "author": "Jay",
    "usdz": "",
    "source": "assets/models/fish-house.glb",
    "poster": "assets/posters/poster_fish-house.png"
  },
  {
    "id": "formation",
    "title": "Formation",
    "description": "",
    "preview": true,
    "author": "",
    "usdz": "",
    "source": "assets/models/formation.glb",
    "poster": "assets/posters/poster_formation.png"
  },
  {
    "id": "green-coral",
    "title": "Green Coral",
    "description": "",
    "preview": true,
    "author": "Jay",
    "usdz": "",
    "source": "assets/models/green-coral.glb",
    "poster": "assets/posters/poster_green-coral.png"
  },
  {
    "id": "knobble_hog_coral",
    "title": "Knobble Hog Coral",
    "description": "",
    "preview": true,
    "author": "",
    "usdz": "",
    "source": "assets/models/knobble_hog_coral.glb",
    "poster": "assets/posters/poster_knobble_hog_coral.png"
  },
  {
    "id": "knobble_hog_nearby",
    "title": "Knobble Hog Nearby",
    "description": "",
    "preview": true,
    "author": "",
    "usdz": "",
    "source": "assets/models/knobble_hog_nearby.glb",
    "poster": "assets/posters/poster_knobble_hog_nearby.png"
  },
  {
    "id": "mask_FILE250630-121332F",
    "title": "Concrete Turtle",
    "description": "",
    "preview": true,
    "author": "Jay",
    "usdz": "",
    "source": "assets/models/mask_FILE250630-121332F.glb",
    "poster": "assets/posters/poster_mask_FILE250630-121332F.png"
  },
  {
    "id": "offering",
    "title": "Offering",
    "description": "",
    "preview": true,
    "author": "",
    "usdz": "",
    "source": "assets/models/offering.glb",
    "poster": "assets/posters/poster_offering.png"
  },
  {
    "id": "pork_belly_baby",
    "title": "Pork Belly Baby",
    "description": "",
    "preview": true,
    "author": "",
    "usdz": "",
    "source": "assets/models/pork_belly_baby.glb",
    "poster": "assets/posters/poster_pork_belly_baby.png"
  },
  {
    "id": "small_coral",
    "title": "Small Coral",
    "description": "",
    "preview": true,
    "author": "",
    "usdz": "",
    "source": "assets/models/small_coral.glb",
    "poster": "assets/posters/poster_small_coral.png"
  },
  {
    "id": "statue",
    "title": "Statue",
    "description": "",
    "preview": true,
    "author": "",
    "usdz": "",
    "source": "assets/models/statue.glb",
    "poster": "assets/posters/poster_statue.png"
  },
  {
    "id": "table",
    "title": "Table",
    "description": "",
    "preview": true,
    "author": "Paula",
    "usdz": "",
    "source": "assets/models/table.glb",
    "poster": "assets/posters/poster_table.png"
  },
  {
    "id": "tables_near_buoy",
    "title": "Tables near Buoy",
    "description": "",
    "preview": true,
    "author": "",
    "usdz": "",
    "source": "assets/models/tables_near_buoy.glb",
    "poster": "assets/posters/poster_tables_near_buoy.png"
  },
  {
    "id": "tendrils",
    "title": "Tendrils",
    "description": "",
    "preview": true,
    "author": "",
    "usdz": "",
    "source": "assets/models/tendrils.glb",
    "poster": "assets/posters/poster_tendrils.png"
  },
  {
    "id": "white-coral_FILE250630-120534F",
    "title": "White Coral",
    "description": "",
    "preview": true,
    "author": "Jay",
    "usdz": "",
    "source": "assets/models/white-coral_FILE250630-120534F.glb",
    "poster": "assets/posters/poster_white-coral_FILE250630-120534F.png"
  }
];
