// this file is auto-generated by build-models.js
export const modelData = [
  {
    "id": "archway_FILE250630-092430F",
    "source": "assets/archway_FILE250630-092430F.glb",
    "poster": "assets/poster_archway_FILE250630-092430F.png",
    "title": "archway FILE250630 092430F",
    "description": "",
    "preview": true
  },
  {
    "id": "baby_coral",
    "source": "assets/baby_coral.glb",
    "poster": "assets/poster_baby_coral.png",
    "title": "baby coral",
    "description": "",
    "preview": true
  },
  {
    "id": "beautiful",
    "source": "assets/beautiful.glb",
    "poster": "assets/poster_beautiful.png",
    "title": "beautiful",
    "description": "",
    "preview": true
  },
  {
    "id": "bell",
    "source": "assets/bell.glb",
    "poster": "assets/poster_bell.png",
    "title": "bell",
    "description": "",
    "preview": true
  },
  {
    "id": "big-brain_P6300418",
    "source": "assets/big-brain_P6300418.glb",
    "poster": "assets/poster_big-brain_P6300418.png",
    "title": "big brain P6300418",
    "description": "",
    "preview": true
  },
  {
    "id": "big_gulp_coral",
    "source": "assets/big_gulp_coral.glb",
    "poster": "assets/poster_big_gulp_coral.png",
    "title": "big gulp coral",
    "description": "",
    "preview": true
  },
  {
    "id": "big_gulp_nearby_rocks",
    "source": "assets/big_gulp_nearby_rocks.glb",
    "poster": "assets/poster_big_gulp_nearby_rocks.png",
    "title": "big gulp nearby rocks",
    "description": "",
    "preview": true
  },
  {
    "id": "block-arch_P6300303",
    "source": "assets/block-arch_P6300303.glb",
    "poster": "assets/poster_block-arch_P6300303.png",
    "title": "block arch P6300303",
    "description": "",
    "preview": true
  },
  {
    "id": "boule",
    "source": "assets/boule.glb",
    "poster": "assets/poster_boule.png",
    "title": "boule",
    "description": "",
    "preview": true
  },
  {
    "id": "brain-n-rocks_FILE250630-094721F",
    "source": "assets/brain-n-rocks_FILE250630-094721F.glb",
    "poster": "assets/poster_brain-n-rocks_FILE250630-094721F.png",
    "title": "brain n rocks FILE250630 094721F",
    "description": "",
    "preview": true
  },
  {
    "id": "bumps",
    "source": "assets/bumps.glb",
    "poster": "assets/poster_bumps.png",
    "title": "bumps",
    "description": "",
    "preview": true
  },
  {
    "id": "columnar-coral_FILE250704-094129F",
    "source": "assets/columnar-coral_FILE250704-094129F.glb",
    "poster": "assets/poster_columnar-coral_FILE250704-094129F.png",
    "title": "columnar coral FILE250704 094129F",
    "description": "",
    "preview": true
  },
  {
    "id": "coral-variety-2_P6300279",
    "source": "assets/coral-variety-2_P6300279.glb",
    "poster": "assets/poster_coral-variety-2_P6300279.png",
    "title": "coral variety 2 P6300279",
    "description": "",
    "preview": true
  },
  {
    "id": "coral-variety_GH010101",
    "source": "assets/coral-variety_GH010101.glb",
    "poster": "assets/poster_coral-variety_GH010101.png",
    "title": "coral variety GH010101",
    "description": "",
    "preview": true
  },
  {
    "id": "coral_cliff",
    "source": "assets/coral_cliff.glb",
    "poster": "assets/poster_coral_cliff.png",
    "title": "coral cliff",
    "description": "",
    "preview": true
  },
  {
    "id": "cucumber-mound_FILE250630-094443F",
    "source": "assets/cucumber-mound_FILE250630-094443F.glb",
    "poster": "assets/poster_cucumber-mound_FILE250630-094443F.png",
    "title": "cucumber mound FILE250630 094443F",
    "description": "",
    "preview": true
  },
  {
    "id": "fish-house",
    "source": "assets/fish-house.glb",
    "poster": "assets/poster_fish-house.png",
    "title": "fish house",
    "description": "",
    "preview": true
  },
  {
    "id": "formation",
    "source": "assets/formation.glb",
    "poster": "assets/poster_formation.png",
    "title": "formation",
    "description": "",
    "preview": true
  },
  {
    "id": "green-coral",
    "source": "assets/green-coral.glb",
    "poster": "assets/poster_green-coral.png",
    "title": "green coral",
    "description": "",
    "preview": true
  },
  {
    "id": "knobble_hog_coral",
    "source": "assets/knobble_hog_coral.glb",
    "poster": "assets/poster_knobble_hog_coral.png",
    "title": "knobble hog coral",
    "description": "",
    "preview": true
  },
  {
    "id": "knobble_hog_nearby",
    "source": "assets/knobble_hog_nearby.glb",
    "poster": "assets/poster_knobble_hog_nearby.png",
    "title": "knobble hog nearby",
    "description": "",
    "preview": true
  },
  {
    "id": "mask_FILE250630-121332F",
    "source": "assets/mask_FILE250630-121332F.glb",
    "poster": "assets/poster_mask_FILE250630-121332F.png",
    "title": "mask FILE250630 121332F",
    "description": "",
    "preview": true
  },
  {
    "id": "offering",
    "source": "assets/offering.glb",
    "poster": "assets/poster_offering.png",
    "title": "offering",
    "description": "",
    "preview": true
  },
  {
    "id": "pork_belly_baby",
    "source": "assets/pork_belly_baby.glb",
    "poster": "assets/poster_pork_belly_baby.png",
    "title": "pork belly baby",
    "description": "",
    "preview": true
  },
  {
    "id": "small_coral",
    "source": "assets/small_coral.glb",
    "poster": "assets/poster_small_coral.png",
    "title": "small coral",
    "description": "",
    "preview": true
  },
  {
    "id": "statue",
    "source": "assets/statue.glb",
    "poster": "assets/poster_statue.png",
    "title": "statue",
    "description": "",
    "preview": true
  },
  {
    "id": "table",
    "source": "assets/table.glb",
    "poster": "assets/poster_table.png",
    "title": "table",
    "description": "",
    "preview": true
  },
  {
    "id": "tables_near_buoy",
    "source": "assets/tables_near_buoy.glb",
    "poster": "assets/poster_tables_near_buoy.png",
    "title": "tables near buoy",
    "description": "",
    "preview": true
  },
  {
    "id": "tendrils",
    "source": "assets/tendrils.glb",
    "poster": "assets/poster_tendrils.png",
    "title": "tendrils",
    "description": "",
    "preview": true
  },
  {
    "id": "white-coral_FILE250630-120534F",
    "source": "assets/white-coral_FILE250630-120534F.glb",
    "poster": "assets/poster_white-coral_FILE250630-120534F.png",
    "title": "white coral FILE250630 120534F",
    "description": "",
    "preview": true
  }
];
